#ifndef REDPANDASTOOLBOX_GLOBAL_H
#define REDPANDASTOOLBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REDPANDASTOOLBOX_LIBRARY)
#define REDPANDASTOOLBOX_EXPORT Q_DECL_EXPORT
#else
#define REDPANDASTOOLBOX_EXPORT Q_DECL_IMPORT
#endif

#endif // REDPANDASTOOLBOX_GLOBAL_H
